name: Hourly Cron Job
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Latest Beach Readings
        run: |
          curl --request POST \
          --url 'https://beachbackend.herokuapp.com/import/beaches' \
          --header 'Authorization: Bearer ${{ secrets.API_KEY }}'
        shell: bash
