name: Deploy Backend
on:
  push:
    paths:
      - "apps/backend/**"
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install Dependencies
        working-directory: ./apps/backend
        run: yarn
      - name: Run test
        working-directory: ./apps/backend
        run: yarn test
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "beachbackend" #Must be unique in Heroku
          heroku_email: "matthewnaik@gmail.com"
          appdir: "apps/backend"
